sonar.projectKey=DEFRA_forms-common
sonar.projectName=forms-common
sonar.organization=defra

sonar.links.homepage=https://github.com/DEFRA/forms-common/blob/main/README.md
sonar.links.ci=https://github.com/DEFRA/forms-common/actions
sonar.links.scm=https://github.com/DEFRA/forms-common
sonar.links.issue=https://github.com/DEFRA/forms-common/issues

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/*.test.*
sonar.tests=src
sonar.test.inclusions=**/*.test.*
sonar.cpd.exclusions=**/*.test.*
